/*************************************************************************************

    Grid physics library, www.github.com/paboyle/Grid

    Source file: ./lib/qcd/action/fermion/Fermion_base_aggregate.h

    Copyright (C) 2015

Author: Peter Boyle <pabobyle@ph.ed.ac.uk>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

    See the full license in the file "LICENSE" in the top level distribution directory
*************************************************************************************/
/*  END LEGAL */
#pragma once

/*! \dir
 * This directory contains implementations of a variety of lattice fermions.
 * To get started,
 * see Fermion.h.
 */

/*! \file
 * # Lattice fermions
 *
 * This header `#include`s all relevant headers for fermions in Grid.
 * They are then implemented in the headers in the ``implementation/`` directory.
 *
 * Each implementation
 * (a combination of one of the ``*Impl.h`` files in this directory,
 * and one of those in the ``implementation/`` directory)
 * must be instantiated explicitly.
 * This is handled in the ``instantiation`` directory,
 * with a set of files generated by the file ``generate_instantiations.sh``.
 * A subset of these instantations may selected at `configure` time.
 *
 * The explicit instantiation is only avoidable if we move the above source to headers
 * and end up with include/parse/recompile for EVERY `.cc` file.
 *
 * We maintain here a list of `typedef`s for all supported fermion types.
 * This is more maintainable to do centrally,
 * as more "impl" targets are added,
 * (e.g. extension for gparity, half precision project in comms etc.)
 *
 * The file also includes two ``#include``s for scalar QED:
 *
 * - Scalar.h
 * - Photon.h
 *
 * \todo The files Scalar.h and Photon.h should move to another header,
 * since they are currently included in a file that has since been renamed Fermion.h.
 */

////////////////////////////////////////////
// Fermion operators / actions
////////////////////////////////////////////
#include <Grid/qcd/action/fermion/DWFSlow.h>       // Slow DWF

#include <Grid/qcd/action/fermion/WilsonFermion.h>       // 4d wilson like
/// \cond DO_NOT_DOCUMENT
NAMESPACE_CHECK(Wilson);
/// \endcond
#include <Grid/qcd/action/fermion/WilsonTMFermion.h>       // 4d wilson like
/// \cond DO_NOT_DOCUMENT
NAMESPACE_CHECK(WilsonTM);
/// \endcond
#include <Grid/qcd/action/fermion/WilsonCloverFermion.h> // 4d wilson clover fermions
#include <Grid/qcd/action/fermion/CompactWilsonCloverFermion.h> // 4d compact wilson clover fermions
#include <Grid/qcd/action/fermion/CompactWilsonCloverFermion5D.h> // 5d compact wilson clover fermions
/// \cond DO_NOT_DOCUMENT
NAMESPACE_CHECK(WilsonClover);
/// \endcond
#include <Grid/qcd/action/fermion/WilsonFermion5D.h>     // 5d base used by all 5d overlap types
/// \cond DO_NOT_DOCUMENT
NAMESPACE_CHECK(Wilson5D);
/// \endcond

#include <Grid/qcd/action/fermion/NaiveStaggeredFermion.h>
#include <Grid/qcd/action/fermion/ImprovedStaggeredFermion.h>
#include <Grid/qcd/action/fermion/ImprovedStaggeredFermion5D.h>
/// \cond DO_NOT_DOCUMENT
NAMESPACE_CHECK(Staggered);
/// \endcond

#include <Grid/qcd/action/fermion/CayleyFermion5D.h>     // Cayley types
#include <Grid/qcd/action/fermion/DomainWallFermion.h>
#include <Grid/qcd/action/fermion/DomainWallEOFAFermion.h>
#include <Grid/qcd/action/fermion/MobiusFermion.h>
#include <Grid/qcd/action/fermion/MobiusEOFAFermion.h>
#include <Grid/qcd/action/fermion/ZMobiusFermion.h>
/// \cond DO_NOT_DOCUMENT
NAMESPACE_CHECK(DomainWall);
/// \endcond

#include <Grid/qcd/action/fermion/ScaledShamirFermion.h>
#include <Grid/qcd/action/fermion/MobiusZolotarevFermion.h>
#include <Grid/qcd/action/fermion/ShamirZolotarevFermion.h>
#include <Grid/qcd/action/fermion/OverlapWilsonCayleyTanhFermion.h>
#include <Grid/qcd/action/fermion/OverlapWilsonCayleyZolotarevFermion.h>
#include <Grid/qcd/action/fermion/ContinuedFractionFermion5D.h>               // Continued fraction
#include <Grid/qcd/action/fermion/OverlapWilsonContfracTanhFermion.h>
#include <Grid/qcd/action/fermion/OverlapWilsonContfracZolotarevFermion.h>
#include <Grid/qcd/action/fermion/PartialFractionFermion5D.h>                 // Partial fraction
#include <Grid/qcd/action/fermion/OverlapWilsonPartialFractionTanhFermion.h>
#include <Grid/qcd/action/fermion/OverlapWilsonPartialFractionZolotarevFermion.h>
/// \cond DO_NOT_DOCUMENT
NAMESPACE_CHECK(Overlap);
/// \endcond
///////////////////////////////////////////////////////////////////////////////
// G5 herm -- this has to live in QCD since dirac matrix is not in the broader sector of code
///////////////////////////////////////////////////////////////////////////////
#include <Grid/qcd/action/fermion/g5HermitianLinop.h>

///////////////////////////////////////////////////////////////////////////////
// Fourier accelerated Pauli Villars inverse support
///////////////////////////////////////////////////////////////////////////////
#include <Grid/qcd/action/fermion/WilsonTMFermion5D.h>
/// \cond DO_NOT_DOCUMENT
NAMESPACE_CHECK(WilsonTM5);
/// \endcond

////////////////////////////////////////////////////////////////////////////////
// Move this group to a DWF specific tools/algorithms subdir? 
////////////////////////////////////////////////////////////////////////////////
#include <Grid/qcd/action/fermion/SchurDiagTwoKappa.h>
#include <Grid/qcd/action/fermion/FourierAcceleratedPV.h>
#include <Grid/qcd/action/fermion/PauliVillarsInverters.h>
#include <Grid/qcd/action/fermion/Reconstruct5Dprop.h>
#include <Grid/qcd/action/fermion/MADWF.h>
/// \cond DO_NOT_DOCUMENT
NAMESPACE_CHECK(DWFutils);

NAMESPACE_BEGIN(Grid);
/// \endcond

/*! \name SU(N) Wilson fermions */
/*! @{ */

/*!
 * Doubled, double-precision, Wilson fermion in fundamental representation.
 *
 * \todo Better understand what "doubled" means in this context of e.g. `WilsonImplD2`;
 * but see Grid/simd/Grid_doubled_vector.h.
 */
typedef WilsonFermion<WilsonImplD2> WilsonFermionD2;

/*! Single-precision Wilson fermion in fundamental representation of \f$SU(N)\f$ */
typedef WilsonFermion<WilsonImplF> WilsonFermionF;
/*! Double-precision Wilson fermion in fundamental representation of \f$SU(N)\f$ */
typedef WilsonFermion<WilsonImplD> WilsonFermionD;

/*! Single-precision Wilson fermion in adjoint representation of \f$SU(N)\f$ */
typedef WilsonFermion<WilsonAdjImplF> WilsonAdjFermionF;
/*! Double-precision Wilson fermion in adjoint representation of \f$SU(N)\f$ */
typedef WilsonFermion<WilsonAdjImplD> WilsonAdjFermionD;

/*! Single-precision Wilson fermion in two-index symmetric representation of \f$SU(N)\f$ */
typedef WilsonFermion<WilsonTwoIndexSymmetricImplF> WilsonTwoIndexSymmetricFermionF;
/*! Double-precision Wilson fermion in two-index symmetric representation of \f$SU(N)\f$ */

typedef WilsonFermion<WilsonTwoIndexSymmetricImplD> WilsonTwoIndexSymmetricFermionD;

/*! Single-precision Wilson fermion in two-index antisymmetric representation of \f$SU(N)\f$ */
typedef WilsonFermion<WilsonTwoIndexAntiSymmetricImplF> WilsonTwoIndexAntiSymmetricFermionF;
/*! Double-precision Wilson fermion in two-index antisymmetric representation of \f$SU(N)\f$ */
typedef WilsonFermion<WilsonTwoIndexAntiSymmetricImplD> WilsonTwoIndexAntiSymmetricFermionD;

/*! @} */

/*! \name Sp(2n) Wilson fermions
 * Typically this is written in the literature as \f$Sp(2N)\f$.
 * However,
 * `N` in Grid refers to the size of the matrix;
 * i.e. `N` = \f$2n\f$.
 */
/*! @{ */

/*! Single-precision Wilson fermion in fundamental representation of \f$Sp(2n)\f$ */
typedef WilsonFermion<SpWilsonImplF> SpWilsonFermionF;
/*! Double-precision Wilson fermion in fundamental representation of \f$Sp(2n)\f$ */
typedef WilsonFermion<SpWilsonImplD> SpWilsonFermionD;

/*! Single-precision Wilson fermion in two-index antisymmetric representation of \f$Sp(2n)\f$ */
typedef WilsonFermion<SpWilsonTwoIndexAntiSymmetricImplF> SpWilsonTwoIndexAntiSymmetricFermionF;
/*! Double-precision Wilson fermion in two-index antisymmetric representation of \f$Sp(2n)\f$ */
typedef WilsonFermion<SpWilsonTwoIndexAntiSymmetricImplD> SpWilsonTwoIndexAntiSymmetricFermionD;

/*! Single-precision Wilson fermion in two-index symmetric representation of \f$Sp(2n)\f$.
 * Note that the two-index symmetric representation of \f$Sp(2n)\f$ is equivalent to the adjoint,
 * so there is no `SpWilsonAdjointFermionF`. */
typedef WilsonFermion<SpWilsonTwoIndexSymmetricImplF> SpWilsonTwoIndexSymmetricFermionF;
/*! Double-precision Wilson fermion in two-index symmetric representation of \f$Sp(2n)\f$.
 * Note that the two-index symmetric representation of \f$Sp(2n)\f$ is equivalent to the adjoint,
 * so there is no `SpWilsonAdjointFermionD`. */
typedef WilsonFermion<SpWilsonTwoIndexSymmetricImplD> SpWilsonTwoIndexSymmetricFermionD;

/*! @} */

/*! \name Twisted mass fermion */
/*! @{ */
/*! Doubled, double-precision, twisted-mass Wilson fermion in fundamental representation of \f$SU(N)\f$ */
typedef WilsonTMFermion<WilsonImplD2> WilsonTMFermionD2;
/*! Single-precision twisted-mass Wilson fermion in fundamental representation of \f$SU(N)\f$ */
typedef WilsonTMFermion<WilsonImplF> WilsonTMFermionF;
/*! Double-precision twisted-mass Wilson fermion in fundamental representation of \f$SU(N)\f$ */
typedef WilsonTMFermion<WilsonImplD> WilsonTMFermionD;
/*! @} */

/*! \name Wilson Clover fermions */
/*! @{ */
template <typename WImpl> using WilsonClover = WilsonCloverFermion<WImpl, CloverHelpers<WImpl>>;
template <typename WImpl> using WilsonExpClover = WilsonCloverFermion<WImpl, ExpCloverHelpers<WImpl>>;

/*! Doubled, double-precision, Wilson clover fermion in fundamental representation of \f$SU(N)\f$ */
typedef WilsonClover<WilsonImplD2> WilsonCloverFermionD2;
/*! Single-precision Wilson clover fermion in fundamental representation of \f$SU(N)\f$ */
typedef WilsonCloverWilsonImplF> WilsonCloverFermionF;
/*! Double-precision Wilson clover fermion in fundamental representation of \f$SU(N)\f$ */
typedef WilsonClover<WilsonImplD> WilsonCloverFermionD;

/*! Doubled, double-precision, exponentiated (a.k.a. stabilised) Wilson clover fermion in fundamental representation of \f$SU(N)\f$ */
typedef WilsonExpClover<WilsonImplD2> WilsonExpCloverFermionD2;
/*! Single-precision exponentiated (a.k.a. stabilised) Wilson clover fermion in fundamental representation of \f$SU(N)\f$ */
typedef WilsonExpClover<WilsonImplF> WilsonExpCloverFermionF;
/*! Double-precision exponentiated (a.k.a. stabilised )Wilson clover fermion in fundamental representation of \f$SU(N)\f$ */
typedef WilsonExpClover<WilsonImplD> WilsonExpCloverFermionD;

/*! Single-precision Wilson clover fermion in adjoint representation of \f$SU(N)\f$ */
typedef WilsonClover<WilsonAdjImplF> WilsonCloverAdjFermionF;
/*! Double-precision Wilson clover fermion in adjoint representation of \f$SU(N)\f$ */
typedef WilsonClover<WilsonAdjImplD> WilsonCloverAdjFermionD;

/*! Single-precision Wilson clover fermion in two-index symmetric representation of \f$SU(N)\f$ */
typedef WilsonClover<WilsonTwoIndexSymmetricImplF> WilsonCloverTwoIndexSymmetricFermionF;
/*! Double-precision Wilson clover fermion in two-index symmetric representation of \f$SU(N)\f$ */
typedef WilsonClover<WilsonTwoIndexSymmetricImplD> WilsonCloverTwoIndexSymmetricFermionD;

/*! Single-precision Wilson clover fermion in two-index antisymmetric representation of \f$SU(N)\f$ */
typedef WilsonClover<WilsonTwoIndexAntiSymmetricImplF> WilsonCloverTwoIndexAntiSymmetricFermionF;
/*! Double-precision Wilson clover fermion in two-index antisymmetric representation of \f$SU(N)\f$ */
typedef WilsonClover<WilsonTwoIndexAntiSymmetricImplD> WilsonCloverTwoIndexAntiSymmetricFermionD;
/*! @} */

/*! \name Compact Wilson clover fermions
 *
 * \todo Understand how compact Wilson clover fermions differ from regular Wilson clover fermions
 */
/*! @{ */
template <typename WImpl> using CompactWilsonClover = CompactWilsonCloverFermion<WImpl, CompactCloverHelpers<WImpl>>;
template <typename WImpl> using CompactWilsonClover5D = CompactWilsonCloverFermion5D<WImpl, CompactCloverHelpers<WImpl>>;
template <typename WImpl> using CompactWilsonExpClover = CompactWilsonCloverFermion<WImpl, CompactExpCloverHelpers<WImpl>>;

/*! Doubled, double-precision, compact Wilson clover fermion in fundamental representation of \f$SU(N)\f$ */
typedef CompactWilsonClover<WilsonImplD2> CompactWilsonCloverFermionD2;
/*! Single-precision compact Wilson clover fermion in fundamental representation of \f$SU(N)\f$ */
typedef CompactWilsonClover<WilsonImplF> CompactWilsonCloverFermionF;
/*! Double-precision compact Wilson clover fermion in fundamental representation of \f$SU(N)\f$ */
typedef CompactWilsonClover<WilsonImplD> CompactWilsonCloverFermionD;

/*! Doubled, double-precision, five-dimensional compact Wilson clover fermion in fundamental representation of \f$SU(N)\f$ */
typedef CompactWilsonClover5D<WilsonImplD2> CompactWilsonCloverFermion5DD2;
/*! Single-precision, five-dimensional compact Wilson clover fermion in fundamental representation of \f$SU(N)\f$ */
typedef CompactWilsonClover5D<WilsonImplF> CompactWilsonCloverFermion5DF;
/*! Double-precision, five-dimensional compact Wilson clover fermion in fundamental representation of \f$SU(N)\f$ */
typedef CompactWilsonClover5D<WilsonImplD> CompactWilsonCloverFermion5DD;

/*! Doubled, double-precision, exponentiated (a.k.a. stabilised) Wilson clover fermion in fundamental representation of \f$SU(N)\f$ */
typedef CompactWilsonExpClover<WilsonImplD2> CompactWilsonExpCloverFermionD2;
/*! Single-precision exponentiated (a.k.a. stabilised) Wilson clover fermion in fundamental representation of \f$SU(N)\f$ */
typedef CompactWilsonExpClover<WilsonImplF> CompactWilsonExpCloverFermionF;
/*! Double-precision exponentiated (a.k.a. stabilised) Wilson clover fermion in fundamental representation of \f$SU(N)\f$ */
typedef CompactWilsonExpClover<WilsonImplD> CompactWilsonExpCloverFermionD;

/*! Single-precision exponentiated (a.k.a. stabilised) Wilson clover fermion in adjoint representation of \f$SU(N)\f$ */
typedef CompactWilsonClover<WilsonAdjImplF> CompactWilsonCloverAdjFermionF;
/*! Double-precision exponentiated (a.k.a. stabilised) Wilson clover fermion in adjoint representation of \f$SU(N)\f$ */
typedef CompactWilsonClover<WilsonAdjImplD> CompactWilsonCloverAdjFermionD;

/*! Single-precision exponentiated (a.k.a. stabilised) Wilson clover fermion in two-index symmetric representation of \f$SU(N)\f$ */
typedef CompactWilsonClover<WilsonTwoIndexSymmetricImplF> CompactWilsonCloverTwoIndexSymmetricFermionF;
/*! Double-precision exponentiated (a.k.a. stabilised) Wilson clover fermion in two-index symmetric representation of \f$SU(N)\f$ */
typedef CompactWilsonClover<WilsonTwoIndexSymmetricImplD> CompactWilsonCloverTwoIndexSymmetricFermionD;

/*! Single-precision exponentiated (a.k.a. stabilised) Wilson clover fermion in two-index antisymmetric representation of \f$SU(N)\f$ */
typedef CompactWilsonClover<WilsonTwoIndexAntiSymmetricImplF> CompactWilsonCloverTwoIndexAntiSymmetricFermionF;
/*! Double-precision exponentiated (a.k.a. stabilised) Wilson clover fermion in two-index antisymmetric representation of \f$SU(N)\f$ */
typedef CompactWilsonClover<WilsonTwoIndexAntiSymmetricImplD> CompactWilsonCloverTwoIndexAntiSymmetricFermionD;
/*! @} */

/*! \name Domain Wall fermions (Shamir type) */
/*! @{ */
/*! Single-precision Shamir-type domain wall fermion in the funamdental representation of \f$SU(N)\f$ */
typedef DomainWallFermion<WilsonImplF> DomainWallFermionF;
/*! Double-precision Shamir-type domain wall fermion in the funamdental representation of \f$SU(N)\f$ */
typedef DomainWallFermion<WilsonImplD> DomainWallFermionD;
/*! Doubled, double-precision Shamir-type domain wall fermion in the fundamental representation of \f$SU(N)\f$ */
typedef DomainWallFermion<WilsonImplD2> DomainWallFermionD2;

/*! Single-precision Shamir-type domain wall fermion in the fundamental representation of \f$Sp(2n)\f$ */
typedef DomainWallFermion<SpWilsonImplF> SpDomainWallFermionF;
/*! Double-precision Shamir-type domain wall fermion in the fundamental representation of \f$Sp(2n)\f$ */
typedef DomainWallFermion<SpWilsonImplD> SpDomainWallFermionD;

/*! Doubled, double-precision Shamir-type domain wall fermion in the fundamental representation of SU(N), using the Exact One-Flavour Algorithm */
typedef DomainWallEOFAFermion<WilsonImplD2> DomainWallEOFAFermionD2;
/*! Single-precision Shamir-type domain wall fermion in the fundamental representation of SU(N), using the Exact One-Flavour Algorithm */
typedef DomainWallEOFAFermion<WilsonImplF> DomainWallEOFAFermionF;
/*! Double-precision Shamir-type domain wall fermion in the fundamental representation of SU(N), using the Exact One-Flavour Algorithm */
typedef DomainWallEOFAFermion<WilsonImplD> DomainWallEOFAFermionD;
/*! @} */

/*! \name Möbius domain wall fermions */
/*! @{ */
/*! Doubled, double-precision Möbius domain wall fermion in the fundamental representation of \f$SU(N)\f$ */
typedef MobiusFermion<WilsonImplD2> MobiusFermionD2;
/*! Single-precision Möbius domain wall fermion in the fundamental representation of \f$SU(N)\f$ */
typedef MobiusFermion<WilsonImplF> MobiusFermionF;
/*! Double-precision Möbius domain wall fermion in the fundamental representation of \f$SU(N)\f$ */
typedef MobiusFermion<WilsonImplD> MobiusFermionD;
/*! Single-precision Möbius domain wall fermion in the fundamental representation of \f$Sp(2n)\f$ */
typedef MobiusFermion<SpWilsonImplF> SpMobiusFermionF;
/*! Double-precision Möbius domain wall fermion in the fundamental representation of \f$Sp(2n)\f$ */
typedef MobiusFermion<SpWilsonImplD> SpMobiusFermionD;

/*! Doubled, double-precision Möbius domain wall fermion in the fundamental representation of SU(N), using the Exact One-Flavour Algorithm */
typedef MobiusEOFAFermion<WilsonImplD2> MobiusEOFAFermionD2;
/*! Single-precision Möbius domain wall fermion in the fundamental representation of SU(N), using the Exact One-Flavour Algorithm */
typedef MobiusEOFAFermion<WilsonImplF> MobiusEOFAFermionF;
/*! Double-precision Möbius domain wall fermion in the fundamental representation of SU(N), using the Exact One-Flavour Algorithm */
typedef MobiusEOFAFermion<WilsonImplD> MobiusEOFAFermionD;

/*! Doubled, double-precision zMöbius domain wall fermion in the fundamental representation of \f$SU(N)\f$ */
typedef ZMobiusFermion<ZWilsonImplD2> ZMobiusFermionD2;
/*! Single-precision zMöbius domain wall fermion in the fundamental representation of \f$SU(N)\f$ */
typedef ZMobiusFermion<ZWilsonImplF> ZMobiusFermionF;
/*! Double-precision zMöbius domain wall fermion in the fundamental representation of \f$SU(N)\f$ */
typedef ZMobiusFermion<ZWilsonImplD> ZMobiusFermionD;
/*! Single-precision zMöbius domain wall fermion in the fundamental representation of \f$Sp(2n)\f$ */
typedef ZMobiusFermion<ZSpWilsonImplF> SpZMobiusFermionF;
/*! Double-precision zMöbius domain wall fermion in the fundamental representation of \f$Sp(2n)\f$ */
typedef ZMobiusFermion<ZSpWilsonImplD> SpZMobiusFermionD;
/*! @} */

/*! \name Other domain wall fermion variants */
/*! @{ */
/*! Doubled, double-precision scaled-Shamir domain wall fermion in the fundamental representation of \f$SU(N)\f$ */
typedef ScaledShamirFermion<WilsonImplD2> ScaledShamirFermionD2;
/*! Single-precision scaled-Shamir domain wall fermion in the fundamental representation of \f$SU(N)\f$ */
typedef ScaledShamirFermion<WilsonImplF> ScaledShamirFermionF;
/*! Double-precision scaled-Shamir domain wall fermion in the fundamental representation of \f$SU(N)\f$ */
typedef ScaledShamirFermion<WilsonImplD> ScaledShamirFermionD;

/*! Doubled, double-precision Möbius domain wall fermion with Zolotarev approximation in the fundamental representation of \f$SU(N)\f$ */
typedef MobiusZolotarevFermion<WilsonImplD2> MobiusZolotarevFermionD2;
/*! Single-precision Möbius domain wall fermion with Zolotarev approximation in the fundamental representation of \f$SU(N)\f$ */
typedef MobiusZolotarevFermion<WilsonImplF> MobiusZolotarevFermionF;
/*! Double-precision Möbius domain wall fermion with Zolotarev approximation in the fundamental representation of \f$SU(N)\f$ */
typedef MobiusZolotarevFermion<WilsonImplD> MobiusZolotarevFermionD;
/*! Doubled, double-precision Shamir-type domain wall fermion with Zolotarev approximation in the fundamental representation of \f$SU(N)\f$ */
typedef ShamirZolotarevFermion<WilsonImplD2> ShamirZolotarevFermionD2;
/*! Single-precision Shamir-type domain wall fermion with Zolotarev approximation in the fundamental representation of \f$SU(N)\f$ */
typedef ShamirZolotarevFermion<WilsonImplF> ShamirZolotarevFermionF;
/*! Double-precision Shamir-type domain wall fermion with Zolotarev approximation in the fundamental representation of \f$SU(N)\f$ */
typedef ShamirZolotarevFermion<WilsonImplD> ShamirZolotarevFermionD;
/*! @} */

/*! \name Overlap fermions */
/*! @{ */
typedef OverlapWilsonCayleyTanhFermion<WilsonImplD2> OverlapWilsonCayleyTanhFermionD2;
typedef OverlapWilsonCayleyTanhFermion<WilsonImplF> OverlapWilsonCayleyTanhFermionF;
typedef OverlapWilsonCayleyTanhFermion<WilsonImplD> OverlapWilsonCayleyTanhFermionD;
typedef OverlapWilsonCayleyZolotarevFermion<WilsonImplD2> OverlapWilsonCayleyZolotarevFermionD2;
typedef OverlapWilsonCayleyZolotarevFermion<WilsonImplF> OverlapWilsonCayleyZolotarevFermionF;
typedef OverlapWilsonCayleyZolotarevFermion<WilsonImplD> OverlapWilsonCayleyZolotarevFermionD;
/*! @} */

/*! \name Continued fraction */
/*! @{ */
typedef OverlapWilsonContFracTanhFermion<WilsonImplD2> OverlapWilsonContFracTanhFermionD2;
typedef OverlapWilsonContFracTanhFermion<WilsonImplF> OverlapWilsonContFracTanhFermionF;
typedef OverlapWilsonContFracTanhFermion<WilsonImplD> OverlapWilsonContFracTanhFermionD;
typedef OverlapWilsonContFracZolotarevFermion<WilsonImplD2> OverlapWilsonContFracZolotarevFermionD2;
typedef OverlapWilsonContFracZolotarevFermion<WilsonImplF> OverlapWilsonContFracZolotarevFermionF;
typedef OverlapWilsonContFracZolotarevFermion<WilsonImplD> OverlapWilsonContFracZolotarevFermionD;
/*! @} */

/*! \name Partial fraction */
/*! @{ */
typedef OverlapWilsonPartialFractionTanhFermion<WilsonImplD2> OverlapWilsonPartialFractionTanhFermionD2;
typedef OverlapWilsonPartialFractionTanhFermion<WilsonImplF> OverlapWilsonPartialFractionTanhFermionF;
typedef OverlapWilsonPartialFractionTanhFermion<WilsonImplD> OverlapWilsonPartialFractionTanhFermionD;

typedef OverlapWilsonPartialFractionZolotarevFermion<WilsonImplD2> OverlapWilsonPartialFractionZolotarevFermionD2;
typedef OverlapWilsonPartialFractionZolotarevFermion<WilsonImplF> OverlapWilsonPartialFractionZolotarevFermionF;
typedef OverlapWilsonPartialFractionZolotarevFermion<WilsonImplD> OverlapWilsonPartialFractionZolotarevFermionD;
/*! @} */

/*! \name G-parity
 * This will be a partial list until tested */
/*! @{ */
typedef WilsonFermion<GparityWilsonImplF>     GparityWilsonFermionF;
typedef WilsonFermion<GparityWilsonImplD>     GparityWilsonFermionD;

typedef DomainWallFermion<GparityWilsonImplF> GparityDomainWallFermionF;
typedef DomainWallFermion<GparityWilsonImplD> GparityDomainWallFermionD;

typedef DomainWallEOFAFermion<GparityWilsonImplR> GparityDomainWallEOFAFermionD2;
typedef DomainWallEOFAFermion<GparityWilsonImplF> GparityDomainWallEOFAFermionF;
typedef DomainWallEOFAFermion<GparityWilsonImplD> GparityDomainWallEOFAFermionD;

typedef WilsonTMFermion<GparityWilsonImplR> GparityWilsonTMFermionD2;
typedef WilsonTMFermion<GparityWilsonImplF> GparityWilsonTMFermionF;
typedef WilsonTMFermion<GparityWilsonImplD> GparityWilsonTMFermionD;

typedef MobiusFermion<GparityWilsonImplR> GparityMobiusFermionD2;
typedef MobiusFermion<GparityWilsonImplF> GparityMobiusFermionF;
typedef MobiusFermion<GparityWilsonImplD> GparityMobiusFermionD;

typedef MobiusEOFAFermion<GparityWilsonImplR> GparityMobiusEOFAFermionD2;
typedef MobiusEOFAFermion<GparityWilsonImplF> GparityMobiusEOFAFermionF;
typedef MobiusEOFAFermion<GparityWilsonImplD> GparityMobiusEOFAFermionD;
/*! @} */

/*! \name Staggered fermions
 * \note Staggered fermions are only partially implemented;
 * they may be used for obervable computation,
 * but not for Monte Carlo generation.
 */
/*! @{ */
typedef ImprovedStaggeredFermion<StaggeredImplF> ImprovedStaggeredFermionF;
typedef ImprovedStaggeredFermion<StaggeredImplD> ImprovedStaggeredFermionD;

typedef NaiveStaggeredFermion<StaggeredImplF> NaiveStaggeredFermionF;
typedef NaiveStaggeredFermion<StaggeredImplD> NaiveStaggeredFermionD;

typedef ImprovedStaggeredFermion5D<StaggeredImplF> ImprovedStaggeredFermion5DF;
typedef ImprovedStaggeredFermion5D<StaggeredImplD> ImprovedStaggeredFermion5DD;
/*! @} */

/// \cond DO_NOT_DOCUMENT
NAMESPACE_END(Grid);
/// \endcond

////////////////////
// Scalar QED actions
// TODO: this needs to move to another header after rename to Fermion.h
////////////////////
#include <Grid/qcd/action/scalar/Scalar.h>
#include <Grid/qcd/action/gauge/Photon.h>


